server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Todorov135/java-config-server-values
          default-label: microservices-config
          skipSslValidation: true